import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import React from 'react'
import { Header } from '@/components'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Grocery Store Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={outfit.className}>
        <Header>{children}</Header>
      </body>
    </html>
  )
}
